/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BecomeATestingCentreRouteImport } from './routes/become-a-testing-centre'
import { Route as CpbRouteImport } from './routes/cpb'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as StudyMaterialRouteImport } from './routes/study-material'
import { Route as ValuesRouteImport } from './routes/values'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedBookRouteImport } from './routes/_authenticated/book'
import { Route as AuthenticatedCertificateRouteImport } from './routes/_authenticated/certificate'
import { Route as AuthenticatedConductRouteImport } from './routes/_authenticated/conduct'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedExamRouteImport } from './routes/_authenticated/exam'
import { Route as AuthenticatedExaminerRouteImport } from './routes/_authenticated/examiner'
import { Route as AuthenticatedExperienceRouteImport } from './routes/_authenticated/experience'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedStudyRouteImport } from './routes/_authenticated/study'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as EventsSlugRouteImport } from './routes/events/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeATestingCentreRoute = BecomeATestingCentreRouteImport.update({
  id: '/become-a-testing-centre',
  path: '/become-a-testing-centre',
  getParentRoute: () => rootRouteImport,
} as any)
const CpbRoute = CpbRouteImport.update({
  id: '/cpb',
  path: '/cpb',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyMaterialRoute = StudyMaterialRouteImport.update({
  id: '/study-material',
  path: '/study-material',
  getParentRoute: () => rootRouteImport,
} as any)
const ValuesRoute = ValuesRouteImport.update({
  id: '/values',
  path: '/values',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookRoute = AuthenticatedBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCertificateRoute =
  AuthenticatedCertificateRouteImport.update({
    id: '/certificate',
    path: '/certificate',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConductRoute = AuthenticatedConductRouteImport.update({
  id: '/conduct',
  path: '/conduct',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamRoute = AuthenticatedExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExaminerRoute = AuthenticatedExaminerRouteImport.update({
  id: '/examiner',
  path: '/examiner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExperienceRoute = AuthenticatedExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudyRoute = AuthenticatedStudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/auth': typeof AuthRoute
  '/become-a-testing-centre': typeof BecomeATestingCentreRoute
  '/cpb': typeof CpbRoute
  '/directory': typeof DirectoryRoute
  '/donate': typeof DonateRoute
  '/gallery': typeof GalleryRoute
  '/membership': typeof MembershipRoute
  '/policies': typeof PoliciesRoute
  '/pricing': typeof PricingRoute
  '/report': typeof ReportRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/study-material': typeof StudyMaterialRoute
  '/values': typeof ValuesRoute
  '/verify': typeof VerifyRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/book': typeof AuthenticatedBookRoute
  '/certificate': typeof AuthenticatedCertificateRoute
  '/conduct': typeof AuthenticatedConductRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exam': typeof AuthenticatedExamRoute
  '/examiner': typeof AuthenticatedExaminerRoute
  '/experience': typeof AuthenticatedExperienceRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/study': typeof AuthenticatedStudyRoute
  '/events/$slug': typeof EventsSlugRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/auth': typeof AuthRoute
  '/become-a-testing-centre': typeof BecomeATestingCentreRoute
  '/cpb': typeof CpbRoute
  '/directory': typeof DirectoryRoute
  '/donate': typeof DonateRoute
  '/gallery': typeof GalleryRoute
  '/membership': typeof MembershipRoute
  '/policies': typeof PoliciesRoute
  '/pricing': typeof PricingRoute
  '/report': typeof ReportRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/study-material': typeof StudyMaterialRoute
  '/values': typeof ValuesRoute
  '/verify': typeof VerifyRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/book': typeof AuthenticatedBookRoute
  '/certificate': typeof AuthenticatedCertificateRoute
  '/conduct': typeof AuthenticatedConductRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exam': typeof AuthenticatedExamRoute
  '/examiner': typeof AuthenticatedExaminerRoute
  '/experience': typeof AuthenticatedExperienceRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/study': typeof AuthenticatedStudyRoute
  '/events/$slug': typeof EventsSlugRoute
  '/events': typeof EventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/auth': typeof AuthRoute
  '/become-a-testing-centre': typeof BecomeATestingCentreRoute
  '/cpb': typeof CpbRoute
  '/directory': typeof DirectoryRoute
  '/donate': typeof DonateRoute
  '/gallery': typeof GalleryRoute
  '/membership': typeof MembershipRoute
  '/policies': typeof PoliciesRoute
  '/pricing': typeof PricingRoute
  '/report': typeof ReportRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/study-material': typeof StudyMaterialRoute
  '/values': typeof ValuesRoute
  '/verify': typeof VerifyRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/book': typeof AuthenticatedBookRoute
  '/_authenticated/certificate': typeof AuthenticatedCertificateRoute
  '/_authenticated/conduct': typeof AuthenticatedConductRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/exam': typeof AuthenticatedExamRoute
  '/_authenticated/examiner': typeof AuthenticatedExaminerRoute
  '/_authenticated/experience': typeof AuthenticatedExperienceRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/study': typeof AuthenticatedStudyRoute
  '/events/$slug': typeof EventsSlugRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academy'
    | '/auth'
    | '/become-a-testing-centre'
    | '/cpb'
    | '/directory'
    | '/donate'
    | '/gallery'
    | '/membership'
    | '/policies'
    | '/pricing'
    | '/report'
    | '/reset-password'
    | '/resources'
    | '/study-material'
    | '/values'
    | '/verify'
    | '/admin'
    | '/book'
    | '/certificate'
    | '/conduct'
    | '/dashboard'
    | '/exam'
    | '/examiner'
    | '/experience'
    | '/library'
    | '/profile'
    | '/study'
    | '/events/$slug'
    | '/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academy'
    | '/auth'
    | '/become-a-testing-centre'
    | '/cpb'
    | '/directory'
    | '/donate'
    | '/gallery'
    | '/membership'
    | '/policies'
    | '/pricing'
    | '/report'
    | '/reset-password'
    | '/resources'
    | '/study-material'
    | '/values'
    | '/verify'
    | '/admin'
    | '/book'
    | '/certificate'
    | '/conduct'
    | '/dashboard'
    | '/exam'
    | '/examiner'
    | '/experience'
    | '/library'
    | '/profile'
    | '/study'
    | '/events/$slug'
    | '/events'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/academy'
    | '/auth'
    | '/become-a-testing-centre'
    | '/cpb'
    | '/directory'
    | '/donate'
    | '/gallery'
    | '/membership'
    | '/policies'
    | '/pricing'
    | '/report'
    | '/reset-password'
    | '/resources'
    | '/study-material'
    | '/values'
    | '/verify'
    | '/_authenticated/admin'
    | '/_authenticated/book'
    | '/_authenticated/certificate'
    | '/_authenticated/conduct'
    | '/_authenticated/dashboard'
    | '/_authenticated/exam'
    | '/_authenticated/examiner'
    | '/_authenticated/experience'
    | '/_authenticated/library'
    | '/_authenticated/profile'
    | '/_authenticated/study'
    | '/events/$slug'
    | '/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AcademyRoute: typeof AcademyRoute
  AuthRoute: typeof AuthRoute
  BecomeATestingCentreRoute: typeof BecomeATestingCentreRoute
  CpbRoute: typeof CpbRoute
  DirectoryRoute: typeof DirectoryRoute
  DonateRoute: typeof DonateRoute
  GalleryRoute: typeof GalleryRoute
  MembershipRoute: typeof MembershipRoute
  PoliciesRoute: typeof PoliciesRoute
  PricingRoute: typeof PricingRoute
  ReportRoute: typeof ReportRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResourcesRoute: typeof ResourcesRoute
  StudyMaterialRoute: typeof StudyMaterialRoute
  ValuesRoute: typeof ValuesRoute
  VerifyRoute: typeof VerifyRoute
  EventsSlugRoute: typeof EventsSlugRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-testing-centre': {
      id: '/become-a-testing-centre'
      path: '/become-a-testing-centre'
      fullPath: '/become-a-testing-centre'
      preLoaderRoute: typeof BecomeATestingCentreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cpb': {
      id: '/cpb'
      path: '/cpb'
      fullPath: '/cpb'
      preLoaderRoute: typeof CpbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-material': {
      id: '/study-material'
      path: '/study-material'
      fullPath: '/study-material'
      preLoaderRoute: typeof StudyMaterialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/values': {
      id: '/values'
      path: '/values'
      fullPath: '/values'
      preLoaderRoute: typeof ValuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/book': {
      id: '/_authenticated/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof AuthenticatedBookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificate': {
      id: '/_authenticated/certificate'
      path: '/certificate'
      fullPath: '/certificate'
      preLoaderRoute: typeof AuthenticatedCertificateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conduct': {
      id: '/_authenticated/conduct'
      path: '/conduct'
      fullPath: '/conduct'
      preLoaderRoute: typeof AuthenticatedConductRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exam': {
      id: '/_authenticated/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof AuthenticatedExamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/examiner': {
      id: '/_authenticated/examiner'
      path: '/examiner'
      fullPath: '/examiner'
      preLoaderRoute: typeof AuthenticatedExaminerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/experience': {
      id: '/_authenticated/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof AuthenticatedExperienceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/study': {
      id: '/_authenticated/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof AuthenticatedStudyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBookRoute: typeof AuthenticatedBookRoute
  AuthenticatedCertificateRoute: typeof AuthenticatedCertificateRoute
  AuthenticatedConductRoute: typeof AuthenticatedConductRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExamRoute: typeof AuthenticatedExamRoute
  AuthenticatedExaminerRoute: typeof AuthenticatedExaminerRoute
  AuthenticatedExperienceRoute: typeof AuthenticatedExperienceRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedStudyRoute: typeof AuthenticatedStudyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBookRoute: AuthenticatedBookRoute,
  AuthenticatedCertificateRoute: AuthenticatedCertificateRoute,
  AuthenticatedConductRoute: AuthenticatedConductRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExamRoute: AuthenticatedExamRoute,
  AuthenticatedExaminerRoute: AuthenticatedExaminerRoute,
  AuthenticatedExperienceRoute: AuthenticatedExperienceRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedStudyRoute: AuthenticatedStudyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AcademyRoute: AcademyRoute,
  AuthRoute: AuthRoute,
  BecomeATestingCentreRoute: BecomeATestingCentreRoute,
  CpbRoute: CpbRoute,
  DirectoryRoute: DirectoryRoute,
  DonateRoute: DonateRoute,
  GalleryRoute: GalleryRoute,
  MembershipRoute: MembershipRoute,
  PoliciesRoute: PoliciesRoute,
  PricingRoute: PricingRoute,
  ReportRoute: ReportRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResourcesRoute: ResourcesRoute,
  StudyMaterialRoute: StudyMaterialRoute,
  ValuesRoute: ValuesRoute,
  VerifyRoute: VerifyRoute,
  EventsSlugRoute: EventsSlugRoute,
  EventsIndexRoute: EventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
