INSERT INTO public.cities (name, state, is_active) VALUES
('Visakhapatnam','Andhra Pradesh',false),('Vijayawada','Andhra Pradesh',false),('Guntur','Andhra Pradesh',false),('Tirupati','Andhra Pradesh',false),('Nellore','Andhra Pradesh',false),('Kakinada','Andhra Pradesh',false),('Rajahmundry','Andhra Pradesh',false),('Kurnool','Andhra Pradesh',false),('Anantapur','Andhra Pradesh',false),
('Itanagar','Arunachal Pradesh',false),('Naharlagun','Arunachal Pradesh',false),('Pasighat','Arunachal Pradesh',false),
('Guwahati','Assam',false),('Dibrugarh','Assam',false),('Silchar','Assam',false),('Jorhat','Assam',false),('Tezpur','Assam',false),('Nagaon','Assam',false),
('Patna','Bihar',false),('Gaya','Bihar',false),('Bhagalpur','Bihar',false),('Muzaffarpur','Bihar',false),('Darbhanga','Bihar',false),('Purnia','Bihar',false),('Bodh Gaya','Bihar',false),
('Raipur','Chhattisgarh',false),('Bhilai','Chhattisgarh',false),('Bilaspur','Chhattisgarh',false),('Korba','Chhattisgarh',false),('Durg','Chhattisgarh',false),
('Panaji','Goa',false),('Margao','Goa',false),('Vasco da Gama','Goa',false),('Mapusa','Goa',false),('Calangute','Goa',false),('Candolim','Goa',false),('Anjuna','Goa',false),('Ponda','Goa',false),
('Ahmedabad','Gujarat',false),('Surat','Gujarat',false),('Vadodara','Gujarat',false),('Rajkot','Gujarat',false),('Gandhinagar','Gujarat',false),('Bhavnagar','Gujarat',false),('Jamnagar','Gujarat',false),('Anand','Gujarat',false),('Bhuj','Gujarat',false),
('Gurugram','Haryana',false),('Faridabad','Haryana',false),('Panchkula','Haryana',false),('Karnal','Haryana',false),('Ambala','Haryana',false),('Hisar','Haryana',false),('Rohtak','Haryana',false),('Sonipat','Haryana',false),('Panipat','Haryana',false),('Manesar','Haryana',false),
('Shimla','Himachal Pradesh',false),('Manali','Himachal Pradesh',false),('Dharamshala','Himachal Pradesh',false),('Kasauli','Himachal Pradesh',false),('Solan','Himachal Pradesh',false),('Mandi','Himachal Pradesh',false),('Kullu','Himachal Pradesh',false),
('Ranchi','Jharkhand',false),('Jamshedpur','Jharkhand',false),('Dhanbad','Jharkhand',false),('Bokaro','Jharkhand',false),('Deoghar','Jharkhand',false),
('Bengaluru','Karnataka',false),('Mysuru','Karnataka',false),('Mangaluru','Karnataka',false),('Hubballi','Karnataka',false),('Belagavi','Karnataka',false),('Udupi','Karnataka',false),('Manipal','Karnataka',false),('Davanagere','Karnataka',false),('Kalaburagi','Karnataka',false),('Coorg (Madikeri)','Karnataka',false),
('Kochi','Kerala',false),('Thiruvananthapuram','Kerala',false),('Kozhikode','Kerala',false),('Thrissur','Kerala',false),('Kollam','Kerala',false),('Alappuzha','Kerala',false),('Kannur','Kerala',false),('Kottayam','Kerala',false),('Munnar','Kerala',false),('Wayanad (Kalpetta)','Kerala',false),
('Bhopal','Madhya Pradesh',false),('Indore','Madhya Pradesh',false),('Gwalior','Madhya Pradesh',false),('Jabalpur','Madhya Pradesh',false),('Ujjain','Madhya Pradesh',false),('Khajuraho','Madhya Pradesh',false),('Sagar','Madhya Pradesh',false),
('Pune','Maharashtra',false),('Nagpur','Maharashtra',false),('Nashik','Maharashtra',false),('Thane','Maharashtra',false),('Navi Mumbai','Maharashtra',false),('Aurangabad','Maharashtra',false),('Kolhapur','Maharashtra',false),('Lonavala','Maharashtra',false),('Solapur','Maharashtra',false),('Amravati','Maharashtra',false),('Mahabaleshwar','Maharashtra',false),
('Imphal','Manipur',false),
('Shillong','Meghalaya',false),('Tura','Meghalaya',false),
('Aizawl','Mizoram',false),
('Kohima','Nagaland',false),('Dimapur','Nagaland',false),
('Bhubaneswar','Odisha',false),('Cuttack','Odisha',false),('Puri','Odisha',false),('Rourkela','Odisha',false),('Sambalpur','Odisha',false),('Berhampur','Odisha',false),
('Ludhiana','Punjab',false),('Amritsar','Punjab',false),('Jalandhar','Punjab',false),('Patiala','Punjab',false),('Mohali','Punjab',false),('Bathinda','Punjab',false),('Pathankot','Punjab',false),
('Udaipur','Rajasthan',false),('Jodhpur','Rajasthan',false),('Ajmer','Rajasthan',false),('Kota','Rajasthan',false),('Bikaner','Rajasthan',false),('Pushkar','Rajasthan',false),('Mount Abu','Rajasthan',false),('Alwar','Rajasthan',false),('Bharatpur','Rajasthan',false),
('Gangtok','Sikkim',false),('Pelling','Sikkim',false),
('Coimbatore','Tamil Nadu',false),('Madurai','Tamil Nadu',false),('Tiruchirappalli','Tamil Nadu',false),('Salem','Tamil Nadu',false),('Ooty','Tamil Nadu',false),('Kodaikanal','Tamil Nadu',false),('Tirunelveli','Tamil Nadu',false),('Vellore','Tamil Nadu',false),('Erode','Tamil Nadu',false),('Mahabalipuram','Tamil Nadu',false),
('Hyderabad','Telangana',false),('Secunderabad','Telangana',false),('Warangal','Telangana',false),('Karimnagar','Telangana',false),('Nizamabad','Telangana',false),
('Agartala','Tripura',false),
('Lucknow','Uttar Pradesh',false),('Noida','Uttar Pradesh',false),('Ghaziabad','Uttar Pradesh',false),('Kanpur','Uttar Pradesh',false),('Agra','Uttar Pradesh',false),('Varanasi','Uttar Pradesh',false),('Prayagraj','Uttar Pradesh',false),('Meerut','Uttar Pradesh',false),('Mathura','Uttar Pradesh',false),('Bareilly','Uttar Pradesh',false),('Gorakhpur','Uttar Pradesh',false),('Aligarh','Uttar Pradesh',false),('Greater Noida','Uttar Pradesh',false),
('Haridwar','Uttarakhand',false),('Rishikesh','Uttarakhand',false),('Nainital','Uttarakhand',false),('Mussoorie','Uttarakhand',false),('Roorkee','Uttarakhand',false),('Haldwani','Uttarakhand',false),('Auli','Uttarakhand',false),
('Kolkata','West Bengal',false),('Siliguri','West Bengal',false),('Darjeeling','West Bengal',false),('Howrah','West Bengal',false),('Durgapur','West Bengal',false),('Asansol','West Bengal',false),('Kalimpong','West Bengal',false),
('Port Blair','Andaman & Nicobar Islands',false),
('Chandigarh','Chandigarh',false),
('Daman','Dadra & Nagar Haveli and Daman & Diu',false),('Silvassa','Dadra & Nagar Haveli and Daman & Diu',false),
('New Delhi','Delhi',false),('Dwarka','Delhi',false),('Rohini','Delhi',false),('Saket','Delhi',false),
('Srinagar','Jammu & Kashmir',false),('Jammu','Jammu & Kashmir',false),('Gulmarg','Jammu & Kashmir',false),('Pahalgam','Jammu & Kashmir',false),
('Leh','Ladakh',false),
('Kavaratti','Lakshadweep',false),
('Puducherry','Puducherry',false),('Karaikal','Puducherry',false)
ON CONFLICT DO NOTHING;